#!/bin/bash

# =====[ VISUAL TEST SUITE ]===================================================
#
#	Written by Francois Joubert
#	Oct 2013
#
# =============================================================================

source tacts
source ~/.landobyte/apps/sht/git_env_init

# -----[ TESTS ]---------------------------------------------------------------

test.graph_basic() {
	glo view
}

# -----[ INIT & END ]----------------------------------------------------------

graph.init_suite() {
	export IO_AutoRespondMode=true
	export IO_PrintIndent="  |"

	if [[ ! -d dev/system/.git ]]; then
		git_env_init.run
	fi

	cd dev/system

	return 0
}

graph.end_suite() {
	return 0
}

graph.init_test() {
	[[ -d modules/system ]]

	return 0
}

graph.end_test() {
	return 0
}

# =============================================================================
