#!/usr/bin/env bash

# =====[ GLO ]=================================================================
#
#	Written by Francois Joubert
#	Sep 2013
#
#	Git-flow implementation to create features releases and hotfixes.
#
# =============================================================================

LIB_Root=${0%/*}/libs
source $LIB_Root/stdlib

import utils
import xgit

import glocore		# Core functions [init, task, st, retrieve, etc]
import glogit		# Git synonyms
import glotodo		# Todo
import gloconfig	# Config tools
import glograph		# Graphing
import gloutils		# Helper functions

cmdo2 'version->glo.version'
cmdo2 'selfup->glo.selfupdate'
cmdo2 'internal->glo.internal'
cmdo2 'sandbox->glo.sandbox'

# -----[ VERSION ]-------------------------------------------------------------

# [info-doc version]
# {BLU}version
#   Displays the current version of glo.
glo.version() {
	xgit.version_current
	print $RET
}

# -----[ SELFUP ]--------------------------------------------------------------

# [info-doc selfupdate]
# {BLU}selfupdate
#   Updates itself.
glo.selfupdate() {
	print -i "Checking for updates..."
	cd $(dirname $0)

	if xgit.is_wd_dirty; then
		prompt "Uncommitted changes detected - discard changes and continue?" yes:continue !abort:abort

		git reset --hard HEAD
	fi

	git pull --no-edit
}

# -----[ INTERNAL ]------------------------------------------------------------

glo.internal() {
	print -i "INTERNAL: $@"
	$@
	print -i "RETURN $?: [$RET]"
}

glo.sandbox() {
	echo bla
}

# -----[ MAIN ]----------------------------------------------------------------

io.activate_tracing

cmdo2 run "$@"

terminate ok

# =============================================================================
